[theme]
primaryColor = "#00A86B"  # Cool money green
backgroundColor = "#0E1117"  # Dark background
secondaryBackgroundColor = "#262730"  # Slightly lighter dark background
textColor = "#FFFFFF"  # White text for contrast
font = "sans serif"